#:import ZBarCam kivy_garden.zbarcam.ZBarCam
<AddProductScreen>
    orientation: 'vertical'

    MDToolbar:
        title: "Добавить товар"
    
    MDTabs:
        ScanerTab:
            text: 'Сканер'

            Camera:
                id: camera
                play: False
            #ZBarCam:
            #    play: False

        CustomTab:
            text: 'Вручную'

            ScrollView:
